name: diffwind
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.7.16
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.7
  - glm=0.9.9.8
  - ninja
  - pip
  - pip:
      - numpy==1.21.6
      - Pillow==9.4.0
      - plyfile==0.8.1
      - taichi==1.5.0
      - tqdm==4.66.2
